/**
 * PR Auto-Review Tool - Constants
 *
 * PR自動レビューツールで使用する定数定義
 */

/**
 * Claude Codeによる自動生成コメントのシグネチャ
 *
 * このシグネチャは以下の用途で使用されます:
 * - bot由来のコメント（元のレビュー・返信）を識別
 * - 前回Conversationの抽出
 * - ユーザーの返信カウント時に除外
 */
export const BOT_SIGNATURE = 'Auto-generated by Claude Code';

/**
 * AIエージェントメンション機能
 *
 * 環境変数 AI_AGENT_MENTION でメンション対象を指定できます。
 * - 空文字列（デフォルト）: メンション無効
 * - "jules": Google Jules AIエージェント
 * - "devin": Devin AIエージェント
 * - その他のエージェント名も指定可能
 *
 * 例: AI_AGENT_MENTION=jules → インラインコメントに "@jules" を追加
 */
export const AI_AGENT_MENTION = process.env.AI_AGENT_MENTION || '';
