/**
 * PR Auto-Review Tool - Constants
 *
 * PR自動レビューツールで使用する定数定義
 */

/**
 * Claude Codeによる自動生成コメントのシグネチャ
 *
 * このシグネチャは以下の用途で使用されます:
 * - bot由来のコメント（元のレビュー・返信）を識別
 * - 前回Conversationの抽出
 * - ユーザーの返信カウント時に除外
 */
export const BOT_SIGNATURE = 'Auto-generated by Claude Code';

/**
 * AIエージェント（Julesなど）のGitHubメンション名
 *
 * レビューコメントでAIエージェントにメンションする際に使用
 * @example "@google-labs-jules[bot] この部分を修正してください"
 */
export const AI_AGENT_MENTION = 'google-labs-jules[bot]';
