/**
 * PR Auto-Review Tool - Constants
 *
 * PR自動レビューツールで使用する定数定義
 */

/**
 * Claude Codeによる自動生成コメントのシグネチャ
 *
 * このシグネチャは以下の用途で使用されます:
 * - bot由来のコメントを識別
 * - ユーザーの返信カウント時に除外
 */
export const BOT_SIGNATURE = 'Auto-generated by Claude Code';

/**
 * 元のレビューコメントに付けるマーク（既存）
 */
export const AUTO_REVIEW_MARKER = '🤖 Auto-Review';
