export const GITHUB_OWNER = 'Akamine2001';
export const GITHUB_REPO = 'cc-pulse';

/**
 * AIエージェント（Julesなど）のGitHubメンション名
 *
 * レビューコメントでAIエージェントにメンションする際に使用
 * Google Julesが自動的にレビューコメントを読んで修正を実装します
 * @example "@jules この部分を修正してください"
 */
export const AI_AGENT_MENTION = 'jules';

/**
 * Claude Codeによる自動生成コメントのシグネチャ
 *
 * このシグネチャは以下の用途で使用されます:
 * - bot由来のコメント（元のレビュー・返信）を識別
 * - 前回Conversationの抽出
 * - ユーザーの返信カウント時に除外
 */
export const BOT_SIGNATURE = 'Auto-generated by Claude Code';
